### ISSUE TITLE
credhub --version "panic: runtime error: invalid memory address or nil pointer dereference" 1.5.2

### ISSUE THREAD

**Issue by patrickhuber** [cloudfoundry-incubator/credhub-cli#32]
## Description

credhub  --version panics for me on on Ubuntu LTS 16.04.

## Installation steps

```
wget https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/1.5.2/credhub-linux-1.5.2.tgz
tar xfv credhub-linux-1.5.2.tgz
sudo mv credhub /usr/local/bin/credhub
sudo chmod +x  /usr/local/bin/credhub
```

## Linux Kernel Version

```
$ uname -r
4.4.0-101-generic
```

## Ubuntu Version info

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

## Error 
```
$ credhub --version
CLI Version: 1.5.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x691d26]

goroutine 1 [running]:
github.com/cloudfoundry-incubator/credhub-cli/credhub.(*CredHub).Request(0x0, 0x7a0024, 0x3, 0x7a1fd4, 0xc, 0xc4201264b0, 0x0, 0x0, 0x40000000000, 0xc4200f14c0, ...)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/credhub/request.go:20 +0x26
github.com/cloudfoundry-incubator/credhub-cli/credhub.(*CredHub).find(0x0, 0x7a05e1, 0x5, 0x7a037e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/credhub/find.go:54 +0x187
github.com/cloudfoundry-incubator/credhub-cli/credhub.(*CredHub).FindAllPaths(0x0, 0x7b1144, 0x3f, 0x0, 0x0, 0x0)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/credhub/find.go:26 +0x73
github.com/cloudfoundry-incubator/credhub-cli/commands.PrintVersion(0x46e65b, 0x725560)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/commands/version.go:22 +0x144
github.com/cloudfoundry-incubator/credhub-cli/commands.init.1.func1()
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/commands/version.go:39 +0x22
reflect.Value.call(0x720c20, 0x980238, 0x193, 0x7a0206, 0x4, 0x0, 0x0, 0x0, 0x720c20, 0x26de0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x720c20, 0x980238, 0x193, 0x0, 0x0, 0x0, 0xc400026de0, 0x712de0, 0x980238)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Option).call(0xc4201236c0, 0x0, 0x193, 0x94f980)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/option.go:384 +0x3e5
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Option).set(0xc4201236c0, 0x0, 0x7408c0, 0xc420126360)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/option.go:224 +0x2ba
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).parseOption(0xc4200522a0, 0xc4200fad80, 0x7ffd9b550931, 0x7, 0xc4201236c0, 0x6e2301, 0x0, 0x7, 0x79fe43)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:509 +0x81e
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).parseLong(0xc4200522a0, 0xc4200fad80, 0x7ffd9b550931, 0x7, 0x0, 0x7ffd9b550931, 0x7)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:564 +0xbb
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4200522a0, 0xc42000c070, 0x1, 0x1, 0x4123b8, 0x10, 0x752c00, 0xc4200f1f01, 0xc42003dde0)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:265 +0x33b
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc4200522a0, 0xc42003dde0, 0x2, 0xc4200522a0, 0x405ea4, 0xc42005c058)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/main.go:25 +0xc0
```

**Comment by patrickhuber** [comment]
Also confirmed on Windows 10:

## Windows version

```
C:\WINDOWS\system32>ver

Microsoft Windows [Version 10.0.16299.125]
```

## Error
```
C:\WINDOWS\system32>credhub --version
CLI Version: 1.5.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x692aad]

goroutine 1 [running]:
github.com/cloudfoundry-incubator/credhub-cli/credhub.(*CredHub).Request(0x0, 0x7acd85, 0x3, 0x7aed66, 0xc, 0xc042122db0, 0x0, 0x0, 0x40000000000, 0xc04206f4c0, ...)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/credhub/request.go:20 +0x2d
github.com/cloudfoundry-incubator/credhub-cli/credhub.(*CredHub).find(0x0, 0x7ad3aa, 0x5, 0x7ad138, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/credhub/find.go:54 +0x18e
github.com/cloudfoundry-incubator/credhub-cli/credhub.(*CredHub).FindAllPaths(0x0, 0x7bf196, 0x3f, 0x0, 0x0, 0x0)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/credhub/find.go:26 +0x7a
github.com/cloudfoundry-incubator/credhub-cli/commands.PrintVersion(0x46cc12, 0x732880)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/commands/version.go:22 +0x14b
github.com/cloudfoundry-incubator/credhub-cli/commands.init.1.func1()
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/commands/version.go:39 +0x29
reflect.Value.call(0x72e140, 0x98afb8, 0x193, 0x7acfb0, 0x4, 0x0, 0x0, 0x0, 0x72e140, 0x27200, ...)
        /usr/local/go/src/reflect/value.go:434 +0x90c
reflect.Value.Call(0x72e140, 0x98afb8, 0x193, 0x0, 0x0, 0x0, 0xc000027200, 0x720200, 0x98afb8)
        /usr/local/go/src/reflect/value.go:302 +0xab
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Option).call(0xc042131040, 0x0, 0x193, 0x95a520)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/option.go:384 +0x3ec
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Option).set(0xc042131040, 0x0, 0x74dda0, 0xc042122c60)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/option.go:224 +0x2c1
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).parseOption(0xc04204a2a0, 0xc0420fcd80, 0xc0420100b2, 0x7, 0xc042131040, 0x1, 0x0, 0x1, 0xffffffffffffffff)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:509 +0x833
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).parseLong(0xc04204a2a0, 0xc0420fcd80, 0xc0420100b2, 0x7, 0x0, 0xc0420100b2, 0x7)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:564 +0xc2
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc04204a2a0, 0xc0420023d0, 0x1, 0x1, 0x41109f, 0x10, 0x75fb80, 0xc04206ff01, 0xc042045dc0)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:265 +0x327
github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc04204a2a0, 0xc042045dc0, 0x2, 0xc04204a2a0, 0x4044ab, 0xc04200e0b8)
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x78
main.main()
        /tmp/build/8dc578f1/go/src/github.com/cloudfoundry-incubator/credhub-cli/main.go:25 +0xc7
```

**Comment by patrickhuber** [comment]
Looks like an existing issue is open for this:

 #28
