### ISSUE TITLE
credhub --version results in panic

### ISSUE THREAD

**Issue by terminatingcode** [cloudfoundry-incubator/credhub-cli#48]
What version of the credhub cli you are using?
`1.7.7`

If you were attempting to accomplish a task, what was it you were attempting to do?
credhub login (eventually) but encountering cert issues which has not happened to us before on this env.

What did you expect to happen?
```
$ credhub --version
CLI Version: 1.7.7
```

What was the actual behavior?
```
$ credhub --version
CLI Version: 1.7.7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12f6d19]

goroutine 1 [running]:
code.cloudfoundry.org/credhub-cli/credhub.(*CredHub).Request(0x0, 0x1425be2, 0x3, 0x1427c96, 0xc, 0xc42033eab0, 0x0, 0x0, 0x1, 0x4002011b488, ...)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/credhub/request.go:20 +0x29
code.cloudfoundry.org/credhub-cli/credhub.(*CredHub).find(0x0, 0x14261f6, 0x5, 0x1425f80, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/credhub/find.go:54 +0x197
code.cloudfoundry.org/credhub-cli/credhub.(*CredHub).FindAllPaths(0x0, 0x1438a48, 0x3f, 0x0, 0x0, 0x0)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/credhub/find.go:26 +0x73
code.cloudfoundry.org/credhub-cli/commands.PrintVersion(0x106b91b, 0x1396c00)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/commands/version.go:23 +0x23c
code.cloudfoundry.org/credhub-cli/commands.init.1.func1()
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/commands/version.go:41 +0x22
reflect.Value.call(0x1391c40, 0x1649860, 0x193, 0x1425dd8, 0x4, 0x0, 0x0, 0x0, 0x1391c40, 0x2e680, ...)
    /usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x1391c40, 0x1649860, 0x193, 0x0, 0x0, 0x0, 0xc40002e680, 0x1384040, 0x1649860)
    /usr/local/go/src/reflect/value.go:302 +0xa4
code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Option).call(0xc420155040, 0x0, 0x193, 0x1610a60)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags/option.go:384 +0x3e5
code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Option).set(0xc420155040, 0x0, 0x13b4ca0, 0xc420146f30)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags/option.go:224 +0x2ba
code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).parseOption(0xc4200682a0, 0xc4201230e0, 0x7ffeefbfd94a, 0x7, 0xc420155040, 0x134bf01, 0x0, 0x7, 0x14259e3)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:509 +0x81e
code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).parseLong(0xc4200682a0, 0xc4201230e0, 0x7ffeefbfd94a, 0x7, 0x0, 0x7ffeefbfd94a, 0x7)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:564 +0xbb
code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4200682a0, 0xc42000a090, 0x1, 0x1, 0x10109e8, 0x10, 0x13cba40, 0xc42011bf01, 0xc4201502a0)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:265 +0x33b
code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc4200682a0, 0xc4201502a0, 0x2, 0xc4200682a0, 0x1004354, 0xc42001c0b8)
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
    /tmp/build/8dc578f1/go/src/code.cloudfoundry.org/credhub-cli/main.go:70 +0xc0
```

**Comment by mdelillo** [comment]
@terminatingcode upgrading to the latest version of the CLI should fix this issue. If you are trying to use the CLI with a 1.7.x or 1.9.x server, it will soon be backwards compatible. You can track that [here](https://www.pivotaltracker.com/story/show/160565578).
